stages:
- name: Build
  steps:
  - runScriptConfig:
      image: bayesimpact/react-base
      shellScript: |-
        yarn
        yarn test --coverage
        yarn build
- name: Publish
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: sappachok/wunca39:version-${CICD_EXECUTION_SEQUENCE}
## external registry
      pushRemote: true
      registry: index.docker.io
- name: Deploy
  steps:
  - applyYamlConfig:
      path: ./deployment.yaml
timeout: 60
branch:
  include:
  - master
